symbols = [
    "CHTR",
    "CMCSA",
    "LYV",
    "VZ",
    "HAS",
    "MAR",
    "SBUX",
    "TPR",
    "BG",
    "GIS",
    "KHC",
    "TAP",
    "EOG",
    "MPC",
    "PSX",
    "VLO",
    "ALL",
    "CINF",
    "COIN",
    "HIG",
    "BSX",
    "DGX",
    "SOLV",
    "UHS",
    "ETN",
    "PCAR",
    "TT",
    "URI",
    "APH",
    "GLW",
    "TDY",
    "WDAY",
    "FCX",
    "LIN",
    "LYB",
    "STLD",
    "CBRE",
    "EQR",
    "MAA",
    "O",
    "AWK",
    "DTE",
    "DUK",
    "VST",
]
check_every_seconds = 60
wave_window_prices = 10
minimum_wave_rise_percent = 1.0
maximum_loss_percent = 1.0
